# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c038557d03c5d968a60499ad97f3d15ab5babeb584915e22955643f4a855d76eaede8a941db184bceaa0fc3c57609b37789450d74136747c5ff0d26e70f918e0

test:
  secret_key_base: b90c0afd11f418d9b935f260b3371af6b3d625ba9967570ebccc99c86d9a9e1552c155c1af0732203d802228dad0fc95e18a1d3d0bdcc9857951ecdcbb3314e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
